version: "3"

services:
  app:
    container_name: product-review-app-dev
    image: product-review-app-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
